# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Groovekit < Formula
  desc "CLI for GrooveKit - Monitor cron jobs and APIs"
  homepage "https://groovekit.io"
  version "1.1.0"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/scookdev/groovekit-cli/releases/download/v1.1.0/groovekit-cli_1.1.0_Darwin_x86_64.tar.gz"
      sha256 "e11242ae93b285d14b422f084244bf747b5ccb45bfddf86a15b1cacf7a330fe7"

      def install
        bin.install "groovekit"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/scookdev/groovekit-cli/releases/download/v1.1.0/groovekit-cli_1.1.0_Darwin_arm64.tar.gz"
      sha256 "28fc767aae014986470b7183fb4af490f959b715174e75960912d84ec547bd21"

      def install
        bin.install "groovekit"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/scookdev/groovekit-cli/releases/download/v1.1.0/groovekit-cli_1.1.0_Linux_x86_64.tar.gz"
      sha256 "58fa232a036ccfd624f3ec9e9681f98d3b37953d71287afd7ce90c8f723acd0c"
      def install
        bin.install "groovekit"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/scookdev/groovekit-cli/releases/download/v1.1.0/groovekit-cli_1.1.0_Linux_arm64.tar.gz"
      sha256 "f4ffae7e5769d603805922f7e7c85a77202dd3a259ed054b5905b17a43f1a37f"
      def install
        bin.install "groovekit"
      end
    end
  end

  test do
    system "#{bin}/groovekit", "version"
  end
end
