# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class GroovekitCli < Formula
  desc "CLI for GrooveKit - Monitor cron jobs and APIs"
  homepage "https://groovekit.io"
  version "1.0.0"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/scookdev/groovekit-cli/releases/download/v1.0.0/groovekit-cli_1.0.0_Darwin_x86_64.tar.gz"
      sha256 "6398991c60c65af9cdc6ab7ddec0cf6b4d2e0e99cdf770722d3ddaaa2b08a2f4"

      def install
        bin.install "groovekit"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/scookdev/groovekit-cli/releases/download/v1.0.0/groovekit-cli_1.0.0_Darwin_arm64.tar.gz"
      sha256 "8793a592752e2e0217565a8ecb351e0209cc46d02b67b0c26553f0e807c644bc"

      def install
        bin.install "groovekit"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/scookdev/groovekit-cli/releases/download/v1.0.0/groovekit-cli_1.0.0_Linux_x86_64.tar.gz"
      sha256 "5b7ed4f2e6e679c14ad5f88801346bb0d245577be22cc0594981e384a1ee7fe2"
      def install
        bin.install "groovekit"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/scookdev/groovekit-cli/releases/download/v1.0.0/groovekit-cli_1.0.0_Linux_arm64.tar.gz"
      sha256 "83f1ebb657721f3e55fef586d57d79d34f1a69ecefafc6012088d19417f5180d"
      def install
        bin.install "groovekit"
      end
    end
  end

  test do
    system "#{bin}/groovekit", "version"
  end
end
