# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Groovekit < Formula
  desc "CLI for GrooveKit - Monitor cron jobs and APIs"
  homepage "https://groovekit.io"
  version "1.3.1"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/scookdev/groovekit-cli/releases/download/v1.3.1/groovekit-cli_1.3.1_Darwin_x86_64.tar.gz"
      sha256 "5a4ac349cd2fe34fd14268d341930ebec9e70fa33dfdb51ba89459c28b78ad59"

      define_method(:install) do
        bin.install "groovekit"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/scookdev/groovekit-cli/releases/download/v1.3.1/groovekit-cli_1.3.1_Darwin_arm64.tar.gz"
      sha256 "1c0bf22d08631dfd60aabdf69814b896f63d6a0b7593a184ffa5702b87288ce7"

      define_method(:install) do
        bin.install "groovekit"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/scookdev/groovekit-cli/releases/download/v1.3.1/groovekit-cli_1.3.1_Linux_x86_64.tar.gz"
      sha256 "35884ef3998ece4ee168eb0adda9572c5aad759f6f576fbb400b925d4afb7a91"
      define_method(:install) do
        bin.install "groovekit"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/scookdev/groovekit-cli/releases/download/v1.3.1/groovekit-cli_1.3.1_Linux_arm64.tar.gz"
      sha256 "4be76785f4aef550f7c9800bb3a11e9bfd1310417b826957701fd17f03424331"
      define_method(:install) do
        bin.install "groovekit"
      end
    end
  end

  test do
    system "#{bin}/groovekit", "version"
  end
end
